Made git dependancy check verbouse and added net-online check

diff --git a/vim-plugins b/vim-plugins
--- a/vim-plugins
+++ b/vim-plugins
@@ -6,7 +6,17 @@
 
 BUNDLE_DIR="$HOME/etc/vim/bundle"
 
-[ -x "$(command -v git)" ] || exit 1 # needs git
+if [ ! -x "$(command -v git)" ]
+then
+	echo "git is not installed" 1>&2
+	exit 1
+fi
+
+if ! ping -q -w 1 -c 1 8.8.8.8 >/dev/null 2>&1
+then
+	echo "host is offline, cannot check vim plugins" 1>&2
+	exit 1
+fi
 
 if [ ! -d "$BUNDLE_DIR" ]
 then
