Make net check silent and recheck in the background every 5 seconds indefinetly until the net check succeeds.

diff --git a/vim-plugins b/vim-plugins
--- a/vim-plugins
+++ b/vim-plugins
@@ -14,7 +14,10 @@ fi
 
 if ! ping -q -w 1 -c 1 8.8.8.8 >/dev/null 2>&1
 then
-	echo "host is offline, cannot check vim plugins" 1>&2
+	#echo "host is offline, cannot check vim plugins" 1>&2
+
+	(sleep 5 && exec "$0" &) &
+
 	exit 1
 fi
 
